[package]
name = "owasm"
version = "0.1.6"
authors = ["Band Protocol <connect@bandprotocol.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/bandprotocol/d3n/tree/master/owasm"
description = """
TODO
"""

[dependencies]
serde = { version = "1.0.103", features = ["derive"] }
serde_json = "1.0"
json = "0.12.0"

[workspace]
members = ["example", "exec", "parser"]
