[package]
name = "owasm"
version = "0.1.7"
authors = ["Band Protocol <connect@bandprotocol.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/bandprotocol/d3n/tree/master/owasm"
description = """
TODO
"""

[dependencies]
json = "0.12.0"
num = "*"

[workspace]
members = [
    "chaintests/crypto_price",
    "chaintests/crypto_price_borsh",
    "chaintests/main",
    "chaintests/moresilly",
    "chaintests/silly",
    "chaintests/get_env",
    "chaintests/gold_price",
    "chaindebugtests/allocate",
    "chaintests/alphavantage",
    "chaintests/bitcoin_block_count",
    "chaintests/bitcoin_block_hash",
    "chaintests/coingecko_volume",
    "chaintests/crypto_compare_volume",
    "chaintests/eth_gas_station",
    "chaintests/open_sky_network",
    "chaintests/open_weather_map",
    "chaintests/qrng",
    "chaintests/yahoo_price",
]
