version: "3.7"

services:
  validator1-node:
    build:
      context: .
      dockerfile: Dockerfile
    image: band-validator:latest
    environment:
      - PRIVATE_KEY=06be35b56b048c5a6810a47e2ef612eaed735ccb0d7ea4fc409f23f1d1a16e0b
      - NODE_URI=tcp://localhost:26657
    networks:
      bandchain:
        ipv4_address: 172.18.0.11
    command: sh -c "chmod +x ./docker-config/run.sh && ./docker-config/run.sh validator1"

  validator2-node:
    image: band-validator:latest
    environment:
      - PRIVATE_KEY=6abc8ab25298fb4af6adcb9d5831db0ad7c959388f0d947abd2b4c4457ef52ec
      - NODE_URI=tcp://localhost:26657
    networks:
      bandchain:
        ipv4_address: 172.18.0.12
    command: sh -c "chmod +x ./docker-config/run.sh && ./docker-config/run.sh validator2"

  validator3-node:
    image: band-validator:latest
    environment:
      - PRIVATE_KEY=894fc1c7e7666c722ae5f30ba4cb18c546e08f0b2634718c27b80b9d39416dbe
      - NODE_URI=tcp://localhost:26657
    networks:
      bandchain:
        ipv4_address: 172.18.0.13
    command: sh -c "chmod +x ./docker-config/run.sh && ./docker-config/run.sh validator3"

  validator4-node:
    image: band-validator:latest
    environment:
      - PRIVATE_KEY=947f1715251d43de45232fc072e3ca4d823e876cf9f4ef74ad9a5f4ef440937e
      - NODE_URI=tcp://localhost:26657
    networks:
      bandchain:
        ipv4_address: 172.18.0.14
    ports:
      - 26657:26657
    command: sh -c "chmod +x ./docker-config/run.sh && ./docker-config/run.sh validator4"

  light-client:
    image: band-validator:latest
    networks:
      bandchain:
        ipv4_address: 172.18.0.15
    depends_on:
      - validator4-node
    restart: always
    ports:
      - 1317:1317
    command: bandcli rest-server --laddr tcp://0.0.0.0:1317 --node tcp://172.18.0.14:26657 --chain-id bandchain

networks:
  bandchain:
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"
