name: Chain Workflow
on: [push, pull_request]

jobs:
  chain-test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./chain

    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: "1.14.7"

      - name: Install Wabt (wat2wasm)
        run: |
          wget https://github.com/WebAssembly/wabt/releases/download/1.0.17/wabt-1.0.17-ubuntu.tar.gz
          tar -zxf wabt-1.0.17-ubuntu.tar.gz
          sudo cp wabt-1.0.17/bin/wat2wasm /usr/local/bin

      - name: Check go mod cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-chain-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-chain-

      - name: Run chain tests
        run: go test ./...
        working-directory: ${{env.working-directory}}
