name: Owasm Workflow
on: [push, pull_request]

jobs:
  wasm-test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./owasm
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'bandprotocol/bandchain'

    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Install Rust and rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install Wabt (wat2wasm)
        run: |
          wget https://github.com/WebAssembly/wabt/releases/download/1.0.17/wabt-1.0.17-ubuntu.tar.gz
          tar -zxf wabt-1.0.17-ubuntu.tar.gz
          sudo cp wabt-1.0.17/bin/wat2wasm /usr/local/bin

      - name: Check cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-owasm-${{ hashFiles('**/Cargo.lock') }}

      - name: Run owasm tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path owasm/Cargo.toml --all
